config/routes.rb
Kittenparty::Application.routes.draw do
  resources :votes

  resources :topics

  root to: 'topics#index'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	attr_accessible :description, :title, :img
	has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	attr_accessible :topic_id
	belongs_to :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
  @topics = Topic.page params[:page]

  respond_to do |format|
    format.html # index.html.erb
    format.json { render json: @topics }
  end
end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description, :img)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    topic = Topic.find(params[:topic_id])
    vote = topic.votes.build
    vote.save!
    redirect_to(topics_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kitten Party, an MLG production</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<% flash.each do |name, msg| %>
  <div><%= msg %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.text_area :img %>
  </div>
  <div class="actions">
    <%= f.submit 'Make New Kitten!' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div class="container"><br>
  <h1 class="text-center">Kitten Party!</h1><br>
<h2 class="text-center">Vote for your favorite kitty.</h2><br><br>
<div class="row fluid text-center"><img src="http://i57.tinypic.com/311tkwh.jpg" class="img-circle">
<br><br><br>
</div>

  <div class="row-fluid">
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><h2>Kitten Type</h2></th>
      <th><h2>Votes!</h2></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

  <% @topics.each do |topic| %>
  <tr>
  <td><%= link_to topic.title, topic %><br><br><%= button_to 'Read my bio!', topic, method: :get, class: "btn btn-small btn-info" %></td>
    <td><%= pluralize(topic.votes.length, "vote") %></td>
    <td><%= button_to 'Vote now!', votes_path(topic_id: topic.id), method: :post, class: "btn btn-success text-center" %></td>
  </tr>
<% end %>  

</tbody>
</table>
</div>

<%= paginate @topics %>

<br>

<%= link_to 'Add a Kitten!', new_topic_path %><br><br>
</div>

app/views/topics/new.html.erb
<div class="container"><h1>Er Mer Gerrrd A New Kittennn!</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>
</div>

app/views/topics/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

<div class="row-fluid">
	<div class="span8 offset1">
<p>
  <strong>Name:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @topic.description %>
</p>

<p>
	<strong>Check me out:</strong>
	<%= image_tag(@topic.img, class: "img img-circle") %>
</p>

<p>
	<strong>Created at:</strong>
	<%= @topic.created_at %>
</p>
</div>
</div>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>

</div>